=== dancxjo/panergon/artifactml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="application">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="wizard">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string" minOccurs="0"/>
                            <xs:element name="mode" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id" type="xs:string"/>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="choice" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="option" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="value" type="xs:string"/>
                                                                    <xs:attribute name="label" type="xs:string"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="control-panel" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="setting" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="name" type="xs:string"/>
                                                                    <xs:attribute name="value" type="xs:string"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="warning" minOccurs="0" type="xs:string"/>
                                        <xs:element name="question" minOccurs="0" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string"/>
                                    <xs:attribute name="binary" type="xs:boolean" default="false"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="lang" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dancxjo/panergon/applications/installer.xml
<?xml version="1.0" encoding="UTF-8"?>
<application xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../artifactml.xsd" lang="en">
    <wizard>
        <title>ArtifactOS Installer</title>

        <mode id="choose-language">
            <name>Your language</name>
            <choice>
                <option value="en">English</option>
                <option value="es">Español</option>
                <option value="fr">Français</option>
                <option value="de">Deutsch</option>
                <option value="it">Italiano</option>
                <!-- Add more supported languages as necessary -->
            </choice>
        </mode>

        <mode id="execute-archinstall">
            <name>File Locations</name>
            <control-panel>
                <setting name="configLocation" value="/path/to/config/file" />
                <setting name="credentialsLocation" value="/path/to/credentials/file" />
            </control-panel>
        </mode>

        <mode id="choose-device">
            <name>Device to write to</name>
            <warning>This will erase all data on the device you choose.</warning>
            <choice id="device-list">
                <!-- Options will be populated dynamically by JavaScript -->
            </choice>
        </mode>

        <mode id="confirm-write">
            <title>Confirm write</title>
            <choice binary="true">
                <question id="confirm-question">Are you sure you want to delete all data on the selected device?</question>
            </choice>
        </mode>

        <script src="app.js"></script>
    </wizard>
</application>
